-- Relationship of the CarRentalService

ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_EmployeeJob
FOREIGN KEY (Job) REFERENCES JOB(Job_ID)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_EmployeeDetails
FOREIGN KEY (Em_ID) REFERENCES employee_details(Em_ID)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE VEHICLE
ADD CONSTRAINT FK_VehicleType
FOREIGN KEY (Vehi_Type) REFERENCES vehicle_type(TypeName)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE BOOK
ADD CONSTRAINT FK_BookVehi_No
FOREIGN KEY (Vehicle_No) REFERENCES vehicle(Vehicle_No)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE BOOK
ADD CONSTRAINT FK_BookCustomer
FOREIGN KEY (Customer) REFERENCES customer(ID_No)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE customer
ADD CONSTRAINT FK_CustomerPay
FOREIGN KEY (PaymentRefference) REFERENCES payment(Reference_No)
ON DELETE CASCADE ON UPDATE CASCADE;


select * from vehicle;
